// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_GjfUYxOl7Toia8mLdR8ig_tIk53wpsU',
    appId: '1:229424575850:web:283fe02e0df97e54e02113',
    messagingSenderId: '229424575850',
    projectId: 'kombee-50575',
    authDomain: 'kombee-50575.firebaseapp.com',
    storageBucket: 'kombee-50575.firebasestorage.app',
    measurementId: 'G-F3J9FW4BFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDCwF2nNMFnQlnbdsTbA43HRSgwIQcyw',
    appId: '1:229424575850:android:ec4b9f2a8d546548e02113',
    messagingSenderId: '229424575850',
    projectId: 'kombee-50575',
    storageBucket: 'kombee-50575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjblU_V_qR_5Kfr1hSCR_DtG2UQUyusw',
    appId: '1:229424575850:ios:8c137345d2ccd114e02113',
    messagingSenderId: '229424575850',
    projectId: 'kombee-50575',
    storageBucket: 'kombee-50575.firebasestorage.app',
    iosBundleId: 'com.example.mamsti',
  );
}
